Project1
CatOrLeader/Tinkoff_Java_Backend pull request #2
Opened 2023-10-12 07:26 UTC by CatOrLeader

Refactored project1 was uploaded.

2023-10-18 22:33 UTC, kkmikhaylova requested changes
Нужно переработать структуру кода и добавить тестов на логику

2023-10-18 22:33 UTC, kkmikhaylova commented on src/test/java/edu/project1/LogicTest.java
> +    void changeLangCorrect() {
Зачем мы в двух класстах проверяем смену языка? Кажется это ответственность только одного из них. В LogicTest имеет смысл писать тесты на логику

2023-10-18 22:33 UTC, kkmikhaylova commented on src/test/java/edu/project1/ParserTest.java
> +        assertThrows(InputMismatchException.class, parser::askUserLang);
Опять проверка языка, в парсере ей тоже не место, это не его ответственность

2023-10-18 22:33 UTC, kkmikhaylova commented on src/main/java/edu/project1/text/Language.java
> +    RUS {
Если представить, что наш проект вырос и туда добавилось ещё 10 языков, то текущее решение начинает выглядеть избыточным: на каждый язык по классу, словарь закреплен в коде и нет возможности его изменения налету, очень много дополнительного кода, который не упрощает работу с языками.
Здесь имеет смысл пойти по пути хранения словаря в propeties файлике, для каждого языка свой файлик со словарём ключ-значение, список ключей определён и по ним можем вытащить любую строку. Добавление нового языка это добавление одного файла + определение в коде связки язык-файл.
Вроде того: 
`rus.properties`
```
game.start.greeting-msg=Добро пожаловать
game.finish.win-msg=Вы победили
```
Тогда не понадобится класс Text с наследниками для каждого языка, будет только один класс, который по текущему языку (закреплённому в сессии, например) и по ключу вытащит нужную строку
Так как этой части не было в задании, то этот коммент просто на подумать)

2023-10-18 22:33 UTC, kkmikhaylova commented on pom.xml
> +            <artifactId>lombok</artifactId>
Лучше ознакомиться с альтернативами: records из 16 java, либо kotlin

2023-10-18 22:33 UTC, kkmikhaylova commented on src/main/java/edu/project1/Config.java
> +    public void setLang(Text text) {
Кажется язык должен быть закрёплен в сессии, а не в общем конфиге игры

2023-10-18 22:33 UTC, kkmikhaylova commented on src/main/java/edu/project1/Dictionary.java
> +            List.of(new String[] {"Tinkoff", "Java", "Backend"})
А если игрок выбрал русский язык, то словарь от этого не изменится?

2023-10-18 22:33 UTC, kkmikhaylova commented on src/main/java/edu/project1/HangmanGame.java
> +    public HangmanGame(@NotNull Dictionary dict) {
Если метод не используется, его лучше сразу удалить. Со временем такие мёртвые души будут скапливаться в проекте и мешать доработкам, лучше при необходимости дописать метод, чем на старте реализовывать все варианты взаимодействия с новым классов
Аналогично с классом Logic

2023-10-18 22:33 UTC, kkmikhaylova commented on src/main/java/edu/project1/Logic.java
> +public final class Logic {
Название слишком общее, сюда можно чего угодно напихать, классы лучше делать с более узкой направленностью

2023-10-18 22:33 UTC, kkmikhaylova commented on src/main/java/edu/project1/Logic.java
> +    private Session iterate() {
Неочевидные названия функций здесь и ниже

2023-10-18 22:33 UTC, kkmikhaylova commented on src/main/java/edu/project1/Logic.java
> +            if (isWin()) {
Может определение победы вынести в Session? Кажется это имеет больше смысла, чем добавлять дополнительный State.WIN и переопределять его извне

2023-10-18 22:33 UTC, kkmikhaylova commented on src/main/java/edu/project1/Logic.java
> +        String lowercaseWord = word.toLowerCase();
Можно слова сразу хранить в lowercase и пропадёт необходимость в этом повторяющемся действии

2023-10-20 17:53 UTC, CatOrLeader reviewed
Прочитал все замечания, постарался исправить. Спасибо

2023-10-20 17:53 UTC, CatOrLeader commented on src/main/java/edu/project1/text/Language.java
> +    RUS {
Да, хорошее замечание, мне просто было лень подключать сторонние либы или руками парсить пропертя; в основном в проектах я использовал как раз подход, описанный вами. Решил в этот раз не заморачиваться

2023-10-20 21:56 UTC, kkmikhaylova approved these changes
Сделано отлично, за доп активность с языками отдельный лайк 👍🔥

2023-10-20 23:37 UTC, merged