Homework 2
CatOrLeader/Tinkoff_Java_Backend pull request #3
Opened 2023-10-18 15:37 UTC by CatOrLeader

Implemented all tasks from the HW2; tested.

2023-10-20 22:14 UTC, kkmikhaylova requested changes

2023-10-20 22:14 UTC, kkmikhaylova commented on src/main/java/edu/hw2/task1/Task1.java
> +//        var two = new Constant(2);
Хотелось бы это в тестах увидеть)

2023-10-20 22:14 UTC, kkmikhaylova commented on src/main/java/edu/hw2/task2/Square.java
> +        super.setHeight(width);
Парадокс не разрешен, тест из задания не пройдёт
```
static Arguments[] rectangles() {  
    return new Arguments[]{
        Arguments.of(new Rectangle()), 
        Arguments.of(new Square())
    };  
}  
  
@ParameterizedTest  
@MethodSource("rectangles")  
void rectangleArea(Rectangle rect) {  
    rect.setWidth(20);  
    rect.setHeight(10);  
  
    assertThat(rect.area()).isEqualTo(200.0);  
}
```

2023-10-21 00:11 UTC, CatOrLeader commented on src/main/java/edu/hw2/task1/Task1.java
> +//        var two = new Constant(2);
Готово! 🌵

2023-10-21 00:13 UTC, CatOrLeader commented on src/main/java/edu/hw2/task2/Square.java
> +        super.setHeight(width);
Исправил

Добавлю от себя: мне не нравится решение, которое я написал. По идее, по хорошему, нужно вообще запретить преобладание динамической типизации над статической; в случае чего - выбрасывать экзепшны. Как мне кажется, нельзя давать классам изменять статику под собой, лучше оставлять таким, каким объект задумывался изначально 🤔

2023-10-22 19:40 UTC, kkmikhaylova commented on src/main/java/edu/hw2/task2/Square.java
> +        super.setHeight(width);
Тоже не фанат таких воркэраундов, да и целом холиваров по этой теме хватает) Главное, что понял суть 👍

2023-10-22 19:40 UTC, kkmikhaylova approved these changes

2023-10-22 19:57 UTC, merged